### ISSUE TITLE
Version of weather forecast widget gets lost

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-app-builder#46]
See attached screenshot. After installing the weather forecast widget from the Widget catalog, no version number is shown and the "Update" button is shown instead. After clicking on the button, the correct version is shown but upon reloading the page, the version number is gone again and the "Update" button is shown again.

![Screenshot 2021-12-20 133652](https://user-images.githubusercontent.com/44459397/146768457-32465a2a-7f59-4eca-94a9-65f195dd4be0.png)

**Comment by kalpshekhar-sag** [comment]
Hi @haraldmeyer , updating/ installing the widget now should fix this issue.
@DarpanLalani there are other widgets with the same problem because version number is not maintained in manifest. This needs to be informed team wide.
