### ISSUE TITLE
No validation when creating a new application

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-app-builder#47]
There are multiple validation issues when creating a new app:

* When using the name of an application that already exists, no error is shown but the application is just not created
* When entering an application to clone, no error is shown if the application does not exist or is not an App Builder application (e.g. "Cockpit", as "clone application" is terminology that is used elsewhere in C8Y to clone WebSDK applications, it would maybe make sense to clarify that only App Builder applications can be cloned here).
* using an existing context path (e.g. "cockpit") leads to strange behavior (the app seems to be Cockpit but with the selected App Builder logo). Is that intended?

**Comment by DarpanLalani** [comment]
@haraldmeyer  Thanks for highlighting validation bug.  We have fixed and this will be part of 1.3.0 release.
