### ISSUE TITLE
Unable to give users access to specific device groups within App Builder

### ISSUE THREAD

**Issue by NagendraMS** [SoftwareAG/cumulocity-app-builder#48]
Unable to give users access to specific device groups within App Builder. App builder needs inventory admin and read role by default, it we give inventory read and admin role, all device groups will be available to the user. 

There is no mechanism to restrict users for specific device groups within app builder.

**Comment by DarpanLalani** [comment]
With App Builder 1.3.1,  Role based access feature is available. That will help to restrict user to viewing dashboard
