### ISSUE TITLE
White primary color hiding texts of widgets

### ISSUE THREAD

**Issue by simeonthefirst** [SoftwareAG/cumulocity-app-builder#66]
Setting the background of the navigator to white (#FFFFFF) by setting primary color in the configuration-styles section to white will make many parts of the widgets (eg. in the config) disappear, since their background is white and they use primary color for many texts.

For screenshots and further description see: [https://tech.forums.softwareag.com/t/whitelabeling-of-application-builder-apps-problem-with-primary-color-white/263386](https://tech.forums.softwareag.com/t/whitelabeling-of-application-builder-apps-problem-with-primary-color-white/263386) 

It would hard to change all the the widgets (including open source ones)  to not use primary color for texts, so a solution i think of is to make the background of the navigator to be set seperately.

**Comment by SheethalJR** [comment]
This issue has been fixed and it will be available in the next release(Application Builder -1.3.2).
Thank you.

**Comment by simeonthefirst** [comment]
Hello, 
for me the issue does not seem to be fixed with 1.3.2. : Primary color still sets the background of the navigator AND the text and button color in the widgets (eg. Graph widget config) ->navigator background can still not be white because widget config background always is.

**Comment by SheethalJR** [comment]
Hi,
Data points graph widget config looks fine. 
![image](https://user-images.githubusercontent.com/99970126/211493342-74dd21f8-fefb-49eb-a497-84373a1c4a2a.png)

![image](https://user-images.githubusercontent.com/99970126/211494074-ff0d0381-2d13-4d9b-9d8c-e771f575bddb.png)

Can you please share the screenshot of the issue you are facing.
