### ISSUE TITLE
Application Builder should validate app names before saving

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-app-builder#68]
App Builder 1.3.1

Steps to reproduce:
* Create Application named "Dummy"
* Try to create second application named "Dummy"

Observed behavior: No validation is applied before hitting the Save button, instead app creation fails. Suggestion is to validate app names and detect duplicates before submission. The Save button should be disabled if an application with this name already exists.

**Comment by DarpanLalani** [comment]
Fixed in 2.0
