### ISSUE TITLE
Creating App with custom context path fails

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-app-builder#69]
App Builder v.1.3.1 on eu-latest 10.15

Steps to reproduce:
* Create new App named TestABC
* Define a custom context path testabc

Observed behavior:
The App is not created. The following pop up is shown and does not go away:

![image](https://user-images.githubusercontent.com/44459397/202846736-7bc953ce-b5e7-43fa-9a12-d1b87611c44c.png)

Javascript console shows below error:
`app~vendors~app.099739fe9ca413510a8c.js:1068 ERROR Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'activeVersionId')
TypeError: Cannot read properties of undefined (reading 'activeVersionId')
    at m.<anonymous> (app.e5b3cf7fd23ae0972c13.js:1:41121)
    at Generator.next (<anonymous>)
    at o (app.e5b3cf7fd23ae0972c13.js:1:37764)
    at e.invoke (app~vendors~app.099739fe9ca413510a8c.js:3806:7209)
    at Object.onInvoke (app~vendors~app.099739fe9ca413510a8c.js:2028:1773)
    at e.invoke (app~vendors~app.099739fe9ca413510a8c.js:3806:7149)
    at t.run (app~vendors~app.099739fe9ca413510a8c.js:3806:2289)
    at app~vendors~app.099739fe9ca413510a8c.js:3821:2779
    at e.invokeTask (app~vendors~app.099739fe9ca413510a8c.js:3806:7893)
    at Object.onInvokeTask (app~vendors~app.099739fe9ca413510a8c.js:2028:1589)
    at w (app~vendors~app.099739fe9ca413510a8c.js:3821:1957)
    at app~vendors~app.099739fe9ca413510a8c.js:3821:1049
    at o (app.e5b3cf7fd23ae0972c13.js:1:37782)
    at e.invoke (app~vendors~app.099739fe9ca413510a8c.js:3806:7209)
    at Object.onInvoke (app~vendors~app.099739fe9ca413510a8c.js:2028:1773)
    at e.invoke (app~vendors~app.099739fe9ca413510a8c.js:3806:7149)
    at t.run (app~vendors~app.099739fe9ca413510a8c.js:3806:2289)
    at app~vendors~app.099739fe9ca413510a8c.js:3821:2779
    at e.invokeTask (app~vendors~app.099739fe9ca413510a8c.js:3806:7893)
    at Object.onInvokeTask (app~vendors~app.099739fe9ca413510a8c.js:2028:1589)
Eo @ app~vendors~app.099739fe9ca413510a8c.js:1068
handleError @ app~vendors~app.099739fe9ca413510a8c.js:1075
next @ app~vendors~app.099739fe9ca413510a8c.js:2070
i @ app~vendors~app.099739fe9ca413510a8c.js:1904
t.__tryOrUnsub @ app~vendors~app.099739fe9ca413510a8c.js:4294
t.next @ app~vendors~app.099739fe9ca413510a8c.js:4294
t._next @ app~vendors~app.099739fe9ca413510a8c.js:4294
t.next @ app~vendors~app.099739fe9ca413510a8c.js:4294
t.next @ app~vendors~app.099739fe9ca413510a8c.js:4723
emit @ app~vendors~app.099739fe9ca413510a8c.js:1904
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.run @ app~vendors~app.099739fe9ca413510a8c.js:3806
runOutsideAngular @ app~vendors~app.099739fe9ca413510a8c.js:2028
onHandleError @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.handleError @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.runGuarded @ app~vendors~app.099739fe9ca413510a8c.js:3806
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
Zone.__load_patch.n.microtaskDrainDone @ app~vendors~app.099739fe9ca413510a8c.js:3821
b @ app~vendors~app.099739fe9ca413510a8c.js:3806
Promise.then (async)
v @ app~vendors~app.099739fe9ca413510a8c.js:3806
y @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onScheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleMicroTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
C @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
Promise.then (async)
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
O.e.then @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
l @ app~vendors~app.099739fe9ca413510a8c.js:2960
s @ app~vendors~app.099739fe9ca413510a8c.js:2960
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvoke @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.run @ app~vendors~app.099739fe9ca413510a8c.js:3806
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvokeTask @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.runTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
b @ app~vendors~app.099739fe9ca413510a8c.js:3806
Promise.then (async)
v @ app~vendors~app.099739fe9ca413510a8c.js:3806
y @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onScheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleMicroTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
C @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
Promise.then (async)
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
O.e.then @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
l @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
f @ app~vendors~app.099739fe9ca413510a8c.js:2960
fetch @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:4091
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:4356
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
c @ app~vendors~app.099739fe9ca413510a8c.js:4356
client.fetch @ app~vendors~app.099739fe9ca413510a8c.js:4091
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
d @ app~vendors~app.099739fe9ca413510a8c.js:2960
fetch @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
d @ app~vendors~app.099739fe9ca413510a8c.js:2960
list @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
le @ app~vendors~app.099739fe9ca413510a8c.js:2960
list @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app.e5b3cf7fd23ae0972c13.js:1
o @ app.e5b3cf7fd23ae0972c13.js:1
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvoke @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.run @ app~vendors~app.099739fe9ca413510a8c.js:3806
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvokeTask @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.runTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
b @ app~vendors~app.099739fe9ca413510a8c.js:3806
Promise.then (async)
v @ app~vendors~app.099739fe9ca413510a8c.js:3806
y @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onScheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleMicroTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
C @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
Promise.then (async)
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
O.e.then @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
l @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
f @ app~vendors~app.099739fe9ca413510a8c.js:2960
fetch @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:4091
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:4356
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
c @ app~vendors~app.099739fe9ca413510a8c.js:4356
client.fetch @ app~vendors~app.099739fe9ca413510a8c.js:4091
(anonymous) @ app.e5b3cf7fd23ae0972c13.js:1
o @ app.e5b3cf7fd23ae0972c13.js:1
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvoke @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.run @ app~vendors~app.099739fe9ca413510a8c.js:3806
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvokeTask @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.runTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
b @ app~vendors~app.099739fe9ca413510a8c.js:3806
Promise.then (async)
v @ app~vendors~app.099739fe9ca413510a8c.js:3806
y @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onScheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleMicroTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
C @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
Promise.then (async)
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
O.e.then @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
l @ app~vendors~app.099739fe9ca413510a8c.js:2960
s @ app~vendors~app.099739fe9ca413510a8c.js:2960
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvoke @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invoke @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.run @ app~vendors~app.099739fe9ca413510a8c.js:3806
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvokeTask @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.runTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
b @ app~vendors~app.099739fe9ca413510a8c.js:3806
Promise.then (async)
v @ app~vendors~app.099739fe9ca413510a8c.js:3806
y @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onScheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
e.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.scheduleMicroTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
C @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
Promise.then (async)
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
O.e.then @ app~vendors~app.099739fe9ca413510a8c.js:3821
w @ app~vendors~app.099739fe9ca413510a8c.js:3821
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:3821
l @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
f @ app~vendors~app.099739fe9ca413510a8c.js:2960
fetch @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:4091
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:4356
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
c @ app~vendors~app.099739fe9ca413510a8c.js:4356
client.fetch @ app~vendors~app.099739fe9ca413510a8c.js:4091
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
d @ app~vendors~app.099739fe9ca413510a8c.js:2960
fetch @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
d @ app~vendors~app.099739fe9ca413510a8c.js:2960
list @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2960
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
le @ app~vendors~app.099739fe9ca413510a8c.js:2960
list @ app~vendors~app.099739fe9ca413510a8c.js:2960
(anonymous) @ app.e5b3cf7fd23ae0972c13.js:1
(anonymous) @ app.e5b3cf7fd23ae0972c13.js:1
e @ app~vendors~app.099739fe9ca413510a8c.js:3821
f @ app.e5b3cf7fd23ae0972c13.js:1
createApplication @ app.e5b3cf7fd23ae0972c13.js:1
eval @ m.ngfactory.js:224
handleEvent @ app~vendors~app.099739fe9ca413510a8c.js:2150
handleEvent @ app~vendors~app.099739fe9ca413510a8c.js:2157
cg @ app~vendors~app.099739fe9ca413510a8c.js:1833
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2114
(anonymous) @ app~vendors~app.099739fe9ca413510a8c.js:2526
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
onInvokeTask @ app~vendors~app.099739fe9ca413510a8c.js:2028
e.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.runTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
t.invokeTask @ app~vendors~app.099739fe9ca413510a8c.js:3806
p @ app~vendors~app.099739fe9ca413510a8c.js:3837
f @ app~vendors~app.099739fe9ca413510a8c.js:3837
m @ app~vendors~app.099739fe9ca413510a8c.js:3837`

**Comment by DarpanLalani** [comment]
Fixed in 1.3.2
