### ISSUE TITLE
App Builder homepage should detect if the Demo Catalog is installed

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-app-builder#70]
The homepage of App Builder allows for the installation of the Demo Catalog. Regardless of whether the catalog is installed or not, it always shows the same information:

![image](https://user-images.githubusercontent.com/44459397/202859559-550058d0-bb8f-4205-98f5-5cfb156e4887.png)

When clicking on "Install Demo Catalog" when the catalog is already installed, opens the Demo Catalog. 

App Builder should detect if the Demo Catalog is installed and show different information (e.g. "Open Demo Catalog").

**Comment by DarpanLalani** [comment]
Fixed in 2.0
