### ISSUE TITLE
App Builder is missing new standard KPI widget

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-app-builder#71]
Cumulocity IoT 10.15 has a new "KPI Widget"
https://cumulocity.com/releasenotes/release-10-15-0/applications-10-15-0/#10-15-0-25

 which is not available in App Builder 1.3.1 probably because it is built on an older SDK version.

**Comment by DarpanLalani** [comment]
Yes, you are right. App Builder 2.0 will be based on Cumulocity 10.16 and you will get standard KPI widget
