### ISSUE TITLE
In Dashboard Configuration provide the ability to copy the Dashboard URL

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-app-builder#72]
If a dashboard is configured with Visibility "hidden" it will not be shown in any navigation and can only be accessed by accessing its URL. This URL can be constructed by adding the already displayed dashboard id to the following URL:
/apps/app-builder/index.html#/application/<appid>/dashboard/<dashboardid>

As a convenience method it would be great if the table of dashboards in Configuration contained a "Copy URL" button which copied the URL into the clipboard.

**Comment by DarpanLalani** [comment]
In Application Builder 2.0 onwards, you have option to copy dashboard Id into clipboard in dashboard configuration table.
