### ISSUE TITLE
Random Walk & Value simulators should validate min&max values

### ISSUE THREAD

**Issue by haraldmeyer** [SoftwareAG/cumulocity-app-builder#74]
at the moment, it is possible to provide a minimum that is higher than the maximum. This will probably not have the expected behavior.

Also it would be good if the configuration defined if the interval between minimum and maximum is open or closed (i.e. if the minimum and maximum are included).

(edit) Looking at the implementation, my understanding is that the minimum is included but the maximum not.

**Comment by DarpanLalani** [comment]
Fixed in 2.1
