### ISSUE TITLE
Missing ability to change the page's title tag (to fully overwrite c8y branding)

### ISSUE THREAD

**Issue by beabehnisch** [SoftwareAG/cumulocity-app-builder#80]
as a user, I need to be able to fully erase the cumulocity branding in order to ship my custom app to an end-customer (they don't know cumulocity and shouldn't be confused). Instead they should only see the name of my custom app. 
![Screenshot 2023-01-13 at 16 18 13](https://user-images.githubusercontent.com/52067789/212354799-9ff83574-d2e5-4587-aae5-2fd9087d75f8.png)

For the rest of the platform it seems to be working to overwrite the title (If branding feature is configured): 
<img width="257" alt="Screenshot 2023-01-13 at 16 21 38" src="https://user-images.githubusercontent.com/52067789/212355553-95fe9705-263d-4f64-87a9-a1cd3f645056.png">

**Comment by SheethalJR** [comment]
Hi @beabehnisch,

This can be achieved by modifying the **package.json** file in the Application builder source code.
Steps to follow to clone and modify the source code.

1) Clone from [Source Code](https://github.com/SoftwareAG/cumulocity-app-builder).
2) Run **npm i**.
3) Add **"globalTitle": "custom-app-name"** entry in **package.json** file under the **"application"**.
4) Run **npm build** command to build the file. You can find the build file under **/dist** folder.
5) You can upload the zip file in your tenant by navigating to **Administration->Ecosystem->Applications-> Application Builder**.

Kindly let us know if you are facing any issue.

Regards,
Sheethal J R
