### ISSUE TITLE
Enable new apps 'Access without authentication' 

### ISSUE THREAD

**Issue by SAG-HenryChen** [SoftwareAG/cumulocity-app-builder#85]
Currently , the apps created from app-builder are asking for login before access.
Can we provide a configuration that specific app can be accessed without authentication ?

**Comment by DarpanLalani** [comment]
This is not possible out of the box.
However you can customize app builder for anonymous login.
Please refer [Here](https://cumulocity.com/guides/web/tutorials/#remove-login-and-authentication) for more details.
