### ISSUE TITLE
How to setup an image as background for all page of new app

### ISSUE THREAD

**Issue by SAG-HenryChen** [SoftwareAG/cumulocity-app-builder#93]
Dear team,
Is it possible to upload an image as background for all pages of new application ?

**Comment by DarpanLalani** [comment]
Hi, It is not possible from User Interface. However you can download source and customize app builder to include your image as background for html body. you can do that my modifying css index.less file.

If you need to do application specific then you need do custom implementation for that.
You can go through existing branding implementation [here](https://github.com/SoftwareAG/cumulocity-app-builder/tree/master/builder/branding).

In theory, you may need to do following:

Store your image file in file repository. (May be provide upload file option. same like app Icon).
Write custom code to store file Id in app.applicationBuilder.branding. object. (refer existing implementation for appicon [here](https://github.com/SoftwareAG/cumulocity-app-builder/blob/master/builder/branding/branding.service.ts)
write dynamic css in branding.service.ts file.
