### ISSUE TITLE
[SOLVED] I am receiving a unauthorized error and being force to logout after upgrading app-builder with custom version

### ISSUE THREAD

**Issue by mboarettoPIQ** [SoftwareAG/cumulocity-app-builder#96]
I develop some changes of the custom version to allow me to change more css elements on the styling page.

I upload the new version to cumulocity app-builder tenant, and the old applications that were build with the old version let's say the 2.0.0 does not receive the modifications on the new version, let's call it 2.0.1. 

If I made a simple tweak on the application configuration, e.g. application icon, while have the 2.0.1 version of app-builder as active.
Whenever I tried to reach the same application, I am force to logout with a 401 Unauthorized Http error. 

![image](https://github.com/SoftwareAG/cumulocity-app-builder/assets/138504025/0bc236d7-5532-4c8a-9415-a6d9efdc6ea6)

![image](https://github.com/SoftwareAG/cumulocity-app-builder/assets/138504025/517821ee-e3da-4a36-8126-39b509159843)

So, in order to make my current applications work the custom verison of app builder I must duplicate them using the 2.0.1 version, and fix all bugs related to app cloning. It takes a lot of time. 

I want to know if there is a way that I can create my custom verison of app builder, and only update the custom builder app, without having to duplicate all my current apps with the new version of the builder.

OBS: aside from my company tenant I have a free trial tenant, on the free trial the custom app-builder version behaves the way that I want.

**Comment by DarpanLalani** [comment]
Hi, 

If i understood correctly,
If you have created your App with contextPath (while creating app you will get option), then it will run in its own context. Therefore whenever you deploy new version of your custom app builder, those are not applied to existing app.

I would suggest, you clone your existing app(without context path) and your changes will reflect there. 

For error, i guess you changed context path of application builder in package.json (  "contextPath": "app-builder").

**Comment by mboarettoPIQ** [comment]
Hi Darpan Thanks for the reply, I currently cloning all my applications as you mentioned above.

It seems to work fine right now. However I am facing some issues when cloning my applications and it takes me a while to left my cloned applications up and running. 

Is is possible to apply changes on app-builder, without the need of cloning apps?

**Comment by DarpanLalani** [comment]
Its not possible since we don't have direct access to binary of app which is created with context-path.
However, once you bring your app into app-builder context path, your changes will reflect in your app.
Here are steps to bring your app into app-builder context path:

- Go to Application Builder -> Add Application.
- Give name of your application.
- Do not provide any context path.
- Select your existing application from "Clone Existing Application".
- This will clone your app and bring it into Application Builder context.
- Verify your newly created application for all functionalities.

Now you can do your changes in app builder and it will reflect in your app

**Comment by mboarettoPIQ** [comment]
Hi Darpan, Thanks for the reply. 

I've tried the steps that you suggested on previous post, and it worked! The changes are being reflected on new apps and the new dashboards are working 100%

Cloning an existent app without context-path really did the trick to me.

I appreciate the help.
